version: "3"

services:
  vue:
    container_name: atomic-hack-vue
    build: ./vue
    expose:
      - "4173:4173"
    environment:
      VITE_PROXY_URL: ${VITE_PROXY_URL}
    networks:
      - atomic-hack

  fast-api:
    container_name: atomic-hack-fast-api
    depends_on:
      - pgsql
    ports:
      - "5000:5000"
    build: ./fast_api
    expose:
      - "5000:5000"
    environment:
      DEBUG_MODE: ${DEBUG}
      DB_HOST: atomic-hack-pgsql
      DB_PORT: 5432
      DB_USERNAME: ${POSTGRES_LOGIN}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      DB_NAME: ${POSTGRES_DB_NAME}
      YOLO_HOST: atomic-hack-yolo
      YOLO_PORT: ${YOLO_SERVER_PORT}
    networks:
      - atomic-hack

  yolo:
    container_name: atomic-hack-yolo
    depends_on:
      - fast-api
    build: ./yolo
    expose:
      - "65432:65432"
    networks:
      - atomic-hack

  portainer:
    container_name: atomic-hack-portainer
    image: portainer/portainer-ce:latest
    ports:
      - 9443:9443
    volumes:
      - data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped

  pgsql:
    container_name: atomic-hack-pgsql
    image: dockerhub.timeweb.cloud/library/postgres:latest
    ports:
      - "5432:5432"
    environment:
      DEBUG_MODE: ${DEBUG}
      POSTGRES_USERNAME: ${POSTGRES_LOGIN}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB_NAME}
    volumes:
      - atomic-hack-pgsql:/var/lib/postgresql/data
    networks:
      - atomic-hack

networks:
  atomic-hack:
    driver: bridge

volumes:
  data:
  atomic-hack-pgsql:
    driver: local
