version: "3"

services:
  vue-dev:
    container_name: atomic-hack-vue-dev
    build: ./vue
    ports:
      - "5173:5173"
    networks:
      - atomic-hack
    command: npm run dev

  vue-prod:
    container_name: atomic-hack-vue
    build: ./vue
    ports:
      - "4173:4173"
    networks:
      - atomic-hack

networks:
  atomic-hack:
    driver: bridge
